# Generated by Django 4.2.5 on 2023-09-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_bb_short_url_bb_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Цена'),
        ),
    ]
