# Generated by Django 4.2.5 on 2023-09-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_bb_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
    ]
