# Generated by Django 4.2.5 on 2023-10-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_bb_slug_rubric_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
