# Generated by Django 4.2.5 on 2023-10-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_bb_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
